#!/usr/bin/env python3
"""Regenerates src/Shaders.inc from the files in shaders/.

Kept as generated source (and checked in) so the Visual Studio build needs no
extra tooling. Run this after editing any .vert / .frag."""
import pathlib, sys

root = pathlib.Path(__file__).resolve().parent.parent
out = ["// GENERATED by scripts/embed-shaders.py — edit the files in shaders/ instead.\n",
       "#pragma once\n\n", "namespace lxsd\n{\n"]
for name, path in (("kVertexShader", "shaders/slide.vert"),
                   ("kFragmentShader", "shaders/slide.frag")):
    text = (root / path).read_text()
    out.append(f'static const char {name}[] = R"GLSL(\n{text})GLSL";\n\n')
out.append("}// namespace lxsd\n")
(root / "src/Shaders.inc").write_text("".join(out))
print("wrote src/Shaders.inc")
